import XCTest
@testable import PricingStudioCore

final class ProofProvenanceTests: XCTestCase {

    // Pinned fixture generated by the Python SDK
    // (identity_proof.create_provenance_attestation). Signature is verified
    // cross-language in DPYCAuthKit; here we exercise parsing + decision logic
    // with an injected signature validator.
    private let fixtureJSON = #"""
    {"id": "b4319e4165813c5697bbb45c5a84eac4ac8a08cc6f0e5a43039d2ea36ffede34", "pubkey": "c812f06c4a4e8ec1b81fc4394fd3845599a5c36baf986e96da9e7c924e8073c7", "created_at": 1784481570, "kind": 27235, "tags": [["u", "npub_proof_request"], ["sender", "cab7a8a0b79b507ac0f52c5bed3705e0a646d2ca379b1adb9d8dfd2681af7f54"], ["subject", "npub1w4jmdng7hfzy85j0y9eapgtt2qe6v02f88vv8r35zf6zv7339paq26huw2"], ["service", "x"], ["challenge", "bold-hawk-42"], ["nonce", "5be3886aacad70767ba3d9109d0d4cf3"]], "content": "", "sig": "f31d06a6400eb10d6e8305f04c80a62bf066be397f3ba62da76c6f5a6d5fe18e75dca65e73165f52779c7fc3028e49c664176172559c173685a96f7e8e8bca7b"}
    """#
    private let signerHex = "c812f06c4a4e8ec1b81fc4394fd3845599a5c36baf986e96da9e7c924e8073c7"
    private let senderHex = "cab7a8a0b79b507ac0f52c5bed3705e0a646d2ca379b1adb9d8dfd2681af7f54"
    private let subjectNpub = "npub1w4jmdng7hfzy85j0y9eapgtt2qe6v02f88vv8r35zf6zv7339paq26huw2"
    private let challenge = "bold-hawk-42"

    private let ok: (ProofProvenance.AttestationEvent) -> Bool = { _ in true }
    private let bad: (ProofProvenance.AttestationEvent) -> Bool = { _ in false }

    // MARK: - Parsing

    func testParseExtractsFieldsAndTags() {
        let event = ProofProvenance.parse(fixtureJSON)
        XCTAssertNotNil(event)
        XCTAssertEqual(event?.pubkey, signerHex)
        XCTAssertEqual(event?.kind, 27235)
        XCTAssertEqual(event?.tag("u"), "npub_proof_request")
        XCTAssertEqual(event?.tag("sender"), senderHex)
        XCTAssertEqual(event?.tag("challenge"), challenge)
    }

    // MARK: - Verify (bound-field logic; signature injected)

    func testVerifyOK() {
        let v = ProofProvenance.verify(
            attestationJSON: fixtureJSON, expectedSenderPubkeyHex: senderHex,
            expectedSubjectNpub: subjectNpub, expectedChallenge: challenge,
            signatureValidator: ok
        )
        XCTAssertTrue(v.valid)
        XCTAssertEqual(v.reason, .ok)
        XCTAssertEqual(v.signerPubkeyHex, signerHex)
    }

    func testVerifyBadSignature() {
        let v = ProofProvenance.verify(
            attestationJSON: fixtureJSON, expectedSenderPubkeyHex: senderHex,
            expectedSubjectNpub: subjectNpub, expectedChallenge: challenge,
            signatureValidator: bad
        )
        XCTAssertFalse(v.valid)
        XCTAssertEqual(v.reason, .badSignature)
        XCTAssertNil(v.signerPubkeyHex)
    }

    func testVerifySenderMismatch() {
        let v = ProofProvenance.verify(
            attestationJSON: fixtureJSON, expectedSenderPubkeyHex: "deadbeef",
            expectedSubjectNpub: subjectNpub, expectedChallenge: challenge,
            signatureValidator: ok
        )
        XCTAssertEqual(v.reason, .senderMismatch)
        XCTAssertEqual(v.signerPubkeyHex, signerHex) // signer still recovered
    }

    func testVerifyChallengeMismatch() {
        let v = ProofProvenance.verify(
            attestationJSON: fixtureJSON, expectedSenderPubkeyHex: senderHex,
            expectedSubjectNpub: subjectNpub, expectedChallenge: "calm-wolf-99",
            signatureValidator: ok
        )
        XCTAssertEqual(v.reason, .challengeMismatch)
    }

    func testVerifyAbsent() {
        let v = ProofProvenance.verify(
            attestationJSON: nil, expectedSenderPubkeyHex: senderHex,
            expectedSubjectNpub: subjectNpub, expectedChallenge: challenge,
            signatureValidator: ok
        )
        XCTAssertEqual(v.reason, .absent)
    }

    func testVerifyMalformed() {
        let v = ProofProvenance.verify(
            attestationJSON: "{not json", expectedSenderPubkeyHex: senderHex,
            expectedSubjectNpub: subjectNpub, expectedChallenge: challenge,
            signatureValidator: ok
        )
        XCTAssertEqual(v.reason, .malformed)
    }

    // MARK: - Resolution

    func testResolveKnownVsUnknown() {
        XCTAssertEqual(
            ProofProvenance.resolveAgainstKnownOperators(
                signerPubkeyHex: signerHex, knownOperatorPubkeyHexes: [signerHex]),
            .registeredCertified
        )
        XCTAssertEqual(
            ProofProvenance.resolveAgainstKnownOperators(
                signerPubkeyHex: signerHex, knownOperatorPubkeyHexes: ["other"]),
            .unresolved
        )
    }

    // MARK: - Assessment decision table

    private func verified() -> ProofProvenance.Verification {
        ProofProvenance.Verification(valid: true, signerPubkeyHex: signerHex, reason: .ok)
    }

    func testAssessGreenWhenCertifiedWithHistory() {
        let a = ProofProvenance.assess(
            verification: verified(), resolution: .registeredCertified,
            hasPriorHistory: true, resolvedOperatorName: "eXcalibur MCP", claimedService: "x")
        XCTAssertEqual(a.level, .green)
        XCTAssertEqual(a.resolvedIdentity, "eXcalibur MCP")
    }

    func testDirectDeliverySaysVerifiedOperator() {
        // sender == signer (a direct operator DM): claiming the sender IS the
        // operator is correct.
        let a = ProofProvenance.assess(
            verification: verified(), resolution: .registeredCertified,
            hasPriorHistory: true, resolvedOperatorName: "Cypher-MCP",
            claimedService: "Cypher-MCP", viaDeliveryKey: false)
        XCTAssertEqual(a.headline, "Verified operator")
    }

    func testDeliveryKeySaysAttestedNotSent() {
        // Self-DM: delivered from a one-time key (sender), attested by the
        // operator (signer). The verdict must NOT claim the sender IS the
        // operator — it must say the operator ATTESTED it, via a one-time key.
        let a = ProofProvenance.assess(
            verification: verified(), resolution: .registeredCertified,
            hasPriorHistory: true, resolvedOperatorName: "Cypher-MCP",
            claimedService: "Cypher-MCP", viaDeliveryKey: true)
        XCTAssertEqual(a.level, .green, "a valid operator attestation is still green")
        XCTAssertEqual(a.headline, "Operator-signed",
                       "must not read as 'Verified operator' — the sender is a one-time key")
        XCTAssertTrue(a.detail.lowercased().contains("one-time key"))
        XCTAssertTrue(a.detail.lowercased().contains("not the operator"),
                      "must state the sender npub is not the operator's own")
    }

    func testConvenienceDetectsDeliveryKeyMismatch() {
        // The convenience overload derives viaDeliveryKey by comparing the DM's
        // actual sender to the verified signer. A signer != sender → attested.
        let a = ProofProvenance.assess(
            attestationJSON: nil,                       // absent → amber, exercises the plumbing
            expectedSenderPubkeyHex: "deadbeef",
            expectedSubjectNpub: "npub1subject",
            expectedChallenge: "ch",
            knownOperatorPubkeyHexes: [], priorContactPubkeyHexes: [],
            resolvedOperatorName: nil, claimedService: nil,
            signatureValidator: { _ in true })
        // absent attestation → amber "Unverified request"; the point of this
        // test is that the convenience path compiles + wires viaDeliveryKey.
        XCTAssertEqual(a.level, .amber)
    }

    func testAssessAmberFirstContact() {
        let a = ProofProvenance.assess(
            verification: verified(), resolution: .registeredCertified,
            hasPriorHistory: false, resolvedOperatorName: "eXcalibur MCP", claimedService: "x")
        XCTAssertEqual(a.level, .amber)
        XCTAssertEqual(a.resolvedIdentity, "eXcalibur MCP")
    }

    func testAssessAmberNovel() {
        let a = ProofProvenance.assess(
            verification: verified(), resolution: .registeredNovel,
            hasPriorHistory: false, resolvedOperatorName: "eXcalibur MCP", claimedService: "x")
        XCTAssertEqual(a.level, .amber)
    }

    func testAssessRedUnresolvedShowsClaimedIdentityLabeled() {
        // Validly signed, but the key is not a known operator. The verdict stays
        // red and nothing is rendered as *verified* (resolvedIdentity nil), but
        // the claimed identity is surfaced — hiding it is exactly what lets an
        // impostor claiming a recognised name slip past (#105 / excalibur-mcp#243).
        let a = ProofProvenance.assess(
            verification: verified(), resolution: .unresolved,
            hasPriorHistory: false, resolvedOperatorName: "eXcalibur MCP", claimedService: "eXcalibur MCP")
        XCTAssertEqual(a.level, .red)
        XCTAssertNil(a.resolvedIdentity, "red must never render an identity as verified")
        XCTAssertEqual(a.claimedIdentity, "eXcalibur MCP",
                       "the unknown-signer red case must show-and-label the claim, not hide it")
    }

    func testAssessSurfacesSignedReasonOnUnknownSigner() {
        // A validly-signed unknown-signer request that stated a purpose surfaces
        // it alongside the claimed identity — the "why" that makes a stranger's
        // ask judgeable (the second half of the #105 / excalibur-mcp#243 fix).
        let purpose = "I'm drafting your weekly thread and need the Operator to post it."
        let a = ProofProvenance.assess(
            verification: verified(), resolution: .unresolved,
            hasPriorHistory: false, resolvedOperatorName: "eXcalibur MCP",
            claimedService: "eXcalibur MCP", reason: purpose)
        XCTAssertEqual(a.level, .red)
        XCTAssertEqual(a.reason, purpose,
                       "a signed, validly-verified purpose must be surfaced")
    }

    func testAssessSurfacesSignedOrigin() {
        // Operator-observed origin (signed) is surfaced — even on the red
        // unknown-signer case, where "where did this come from" matters most.
        let origin = "US · 203.0.113.0/24 · claude-ai/1.0"
        let a = ProofProvenance.assess(
            verification: verified(), resolution: .unresolved,
            hasPriorHistory: false, resolvedOperatorName: nil,
            claimedService: "Cypher-MCP", reason: nil, origin: origin)
        XCTAssertEqual(a.level, .red)
        XCTAssertEqual(a.origin, origin, "signed, verified origin must be surfaced")
    }

    func testAssessSuppressesOriginWhenSignatureInvalid() {
        let invalid = ProofProvenance.Verification(
            valid: false, signerPubkeyHex: nil, reason: .badSignature)
        let a = ProofProvenance.assess(
            verification: invalid, resolution: .unresolved,
            hasPriorHistory: false, resolvedOperatorName: nil,
            claimedService: "x", reason: nil, origin: "spoofed origin")
        XCTAssertNil(a.origin, "an unverified attestation's origin must not be shown")
    }

    func testAssessSuppressesReasonWhenSignatureInvalid() {
        // A failed attestation carries no trustworthy purpose — a relay/impostor
        // could have supplied it, so it must never be shown.
        let invalid = ProofProvenance.Verification(
            valid: false, signerPubkeyHex: nil, reason: .badSignature)
        let a = ProofProvenance.assess(
            verification: invalid, resolution: .unresolved,
            hasPriorHistory: false, resolvedOperatorName: nil,
            claimedService: "eXcalibur MCP", reason: "totally legit, trust me")
        XCTAssertNil(a.reason,
                     "an unverified attestation's stated purpose must not be shown")
    }

    func testAssessRedInvalidSuppressesIdentity() {
        // A *failed* verification carries no cryptographically-bound claim — there
        // is nothing trustworthy to show, so both identities stay nil.
        let invalid = ProofProvenance.Verification(valid: false, signerPubkeyHex: nil, reason: .badSignature)
        let a = ProofProvenance.assess(
            verification: invalid, resolution: .unresolved,
            hasPriorHistory: false, resolvedOperatorName: "eXcalibur MCP", claimedService: "x")
        XCTAssertEqual(a.level, .red)
        XCTAssertNil(a.resolvedIdentity)
        XCTAssertNil(a.claimedIdentity, "a failed verification has no bound claim to surface")
    }

    func testAssessAmberWhenAbsent() {
        let absent = ProofProvenance.Verification(valid: false, signerPubkeyHex: nil, reason: .absent)
        let a = ProofProvenance.assess(
            verification: absent, resolution: .unresolved,
            hasPriorHistory: false, resolvedOperatorName: nil, claimedService: "x")
        XCTAssertEqual(a.level, .amber, "absent envelope is amber, never green, never red")
    }

    // MARK: - End-to-end convenience (the incident: self-proof from own operator)

    func testEndToEndSelfProofGreen() {
        let a = ProofProvenance.assess(
            attestationJSON: fixtureJSON,
            expectedSenderPubkeyHex: senderHex,
            expectedSubjectNpub: subjectNpub,
            expectedChallenge: challenge,
            knownOperatorPubkeyHexes: [signerHex],   // it's my own registered operator
            priorContactPubkeyHexes: [signerHex],
            resolvedOperatorName: "eXcalibur MCP",
            claimedService: "x",
            signatureValidator: ok
        )
        XCTAssertEqual(a.level, .green)
    }

    func testEndToEndImpostorRed() {
        // Same DM, but the signer is NOT among my known operators → red.
        let a = ProofProvenance.assess(
            attestationJSON: fixtureJSON,
            expectedSenderPubkeyHex: senderHex,
            expectedSubjectNpub: subjectNpub,
            expectedChallenge: challenge,
            knownOperatorPubkeyHexes: [],            // unknown signer
            priorContactPubkeyHexes: [],
            resolvedOperatorName: nil,
            claimedService: "x",
            signatureValidator: ok
        )
        XCTAssertEqual(a.level, .red)
        XCTAssertNil(a.resolvedIdentity)
        XCTAssertEqual(a.claimedIdentity, "x",
                       "an impostor's claim is shown-and-labelled, never hidden")
    }
}
